version: '3.4'

services:
  hr-platform:
    image: ${DOCKER_REGISTRY-}hrplatform
    build:
      context: .
      dockerfile: HR-Platform/Dockerfile
    ports:
    - 9100:80

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - hr-platform

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=maindb
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
      - ./dbscripts:/docker-entrypoint-initdb.d
    ports:
       - 5433:5433
    restart: always
