version: '3.4'

services:
  hr-platform:
    image: ${DOCKER_REGISTRY-}hrplatform
    build:
      context: .
      dockerfile: HR-Platform/Dockerfile
    ports:
    - 9100:80

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=maindb
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
      - ./dbscripts:/docker-entrypoint-initdb.d
    ports:
       - 5432:5432
    restart: always